language: c
compiler:
  - clang
  - gcc
script:
  - cd src
  #- gcc -include src/WAsys_logging.h -std=c90 -O0 -g3 -Wall -coverage src/WAsys_logging.c src/WAsys_logging_usage_demo.c -o WAsys_logging
  - gcc -std=c90 -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"WAsys_logging.d" -MT"WAsys_logging.o" -o "src/WAsys_logging.o" "WAsys_logging.c"
  - gcc -std=c90 -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"WAsys_logging_usage_demo.d" -MT"WAsys_logging_usage_demo.o" -o "WAsys_logging_usage_demo.o" "WAsys_logging_usage_demo.c"
  - gcc -o "WAsys_lib_log"  ./WAsys_logging.o ./WAsys_logging_usage_demo.o   
  - ./WAsys_lib_log
  - gcov WAsys_lib_log