language: c
compiler:
  - clang
  - gcc
script:
  - ls -a
  - gcc -I./src -std=c90 -O0 -g3 -Wall -o WAsys_lib_log src/WAsys_logging.c src/WAsys_logging_usage_demo.c
  - ./WAsys_lib_log
  - gcov WAsys_lib_log